### ISSUE TITLE
Ubuntu 16, fails on s3

### ISSUE THREAD

**Issue by runtman** [arc-ts/ansible-role-apt#3]
Hello, we have been testing this role on new a AWS instances on Ubuntu 16, and the role appears to fail when trying to add a s3 key.

```
"msg": "Failed to download key at s3://s3-eu-west-1.amazonaws.com/x/gpg-pubkey.asc: Request failed: <urlopen error unknown url type: s3>", 
    "retries": 7
```

Relevant config:

```
apt_manage_keys: true
apt_keys:
- id: D5925237
  url: 's3://s3-eu-west-1.amazonaws.com/x/gpg-pubkey.asc'
  validate_certs: false
  state: present

apt_manage_transports: true
apt_transports:
  - s3
```
